"""
add_bank_valuation.py - DEPRECATED shim. Use scripts/ddm_ri.py.

This script produced 8410 セブン銀行's DDM (258) and Residual Income (293)
sheets, but it carried that company's numbers compiled into it: book value
280,491, net income 13,476, DPS [11.00 .. 13.00], ROE [6.1% .. 7.0%], terminal
g 1.5%, and the FY2027(E)..FY2031(E) column labels. Running it on any other bank
would have valued that bank with セブン銀行's dividends.

CLAUDE.md requires ticker-specific values to arrive from data/, so the engine
moved to scripts/ddm_ri.py and the numbers moved to the overrides'
`bank_valuation` block (docs/overrides_schema.md, 型D の節). The formulas are
unchanged - the extracted engine reproduces 8410's 258 / 293 / 276 exactly from
the same inputs.

    python scripts/ddm_ri.py models/<code>_DCF_Model_<date>.xlsx

型D models generated by scripts/generate_dcf.py get these sheets automatically
(Step 8.6); this CLI is for adding them to a workbook by hand.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

if __name__ == "__main__":
    print(__doc__)
    print("ERROR: このスクリプトは scripts/ddm_ri.py に置き換えられました。")
    print("       銘柄固有の値は data/overrides/<code>_overrides.json の "
          "bank_valuation ブロックで供給してください。")
    sys.exit(2)
