"""diff_models.py - compare two DCF workbooks cell-for-cell on the numbers that matter.

Why: "the regenerated model validates" is not the same claim as "the regenerated
model produces the same numbers". A regression test for a template change has to
compare VALUES against the reference workbook, which is what this does.

    python scripts/diff_models.py REFERENCE.xlsx CANDIDATE.xlsx
    python scripts/diff_models.py REF.xlsx CAND.xlsx --tolerance 0.005 --all-sheets

Both files must be recalculated (scripts/recalc_excel_com.py) — the comparison
reads Excel's cached values, so an un-recalced workbook compares as all-empty.

By default it walks a fixed list of decision-relevant cells (WACC, the two DCF
legs, the Target, the reverse-DCF answer, the comps statistics). --all-sheets
additionally diffs every populated cell of every shared sheet, which is how you
find the changes you did not think to look for.

Exit code 1 if any compared cell differs by more than the tolerance.
"""
import argparse
import os
import sys

import openpyxl

# (sheet, cell, label) — resolved against BOTH workbooks; a cell missing on one
# side is reported rather than skipped.
KEY_CELLS = [
    ("Executive Summary", "C9",  "Current Price"),
    ("Executive Summary", "C10", "Target Price (Mid)"),
    ("Executive Summary", "C11", "Recommendation"),
    ("Executive Summary", "C12", "Upside / Downside"),
    ("Executive Summary", "C16", "DCF - PGM implied price"),
    ("Executive Summary", "C17", "DCF - Exit implied price"),
    ("Executive Summary", "C18", "Comps - EV/EBITDA implied [参考]"),
    ("Executive Summary", "C19", "Comps - PER implied [参考]"),
    ("DCF Model", "C6",  "Effective Tax Rate"),
    ("DCF Model", "C7",  "Risk-Free Rate"),
    ("DCF Model", "C8",  "Beta"),
    ("DCF Model", "C9",  "Equity Risk Premium"),
    ("DCF Model", "C10", "Size Premium"),
    ("DCF Model", "C11", "After-tax Cost of Debt"),
    ("DCF Model", "C12", "D/E Ratio"),
    ("DCF Model", "C13", "Terminal Growth"),
    ("DCF Model", "C14", "Exit Multiple"),
    ("DCF Model", "C15", "Fully Diluted Shares"),
    ("DCF Model", "C16", "Net Debt"),
    ("DCF Model", "C17", "Base Year Revenue"),
    ("DCF Model", "C20", "LTM Revenue"),
    ("DCF Model", "C23", "Cost of Equity"),
    ("DCF Model", "C26", "WACC"),
    ("DCF Model", "C53", "EV (PGM)"),
    ("DCF Model", "C54", "Equity Value (PGM)"),
    ("DCF Model", "C55", "Implied Share Price (PGM)"),
    ("DCF Model", "C62", "EV (Exit)"),
    ("DCF Model", "C63", "Equity Value (Exit)"),
    ("DCF Model", "C64", "Implied Share Price (Exit)"),
    ("Reverse DCF", "C10", "RDCF: market EV"),
    ("Reverse DCF", "C17", "RDCF: base-case DCF EV (PGM)"),
    ("Reverse DCF", "C20", "RDCF: gap per share"),
    ("Reverse DCF", "C25", "RDCF Block A: required steady-state OP"),
    ("Reverse DCF", "C26", "RDCF Block A: x cycle peak"),
    ("Reverse DCF", "F49", "RDCF Block B-3: required OP (N=5, model WACC)"),
    ("Reverse DCF", "F54", "RDCF Block B-4: x peak (N=5)"),
    ("Reverse DCF", "C60", "RDCF Block C: required OP"),
    ("Comps Analysis", "D15", "Comps 25th pct EV/EBITDA"),
    ("Comps Analysis", "D16", "Comps median EV/EBITDA"),
    ("Comps Analysis", "D17", "Comps 75th pct EV/EBITDA"),
    ("Comps Analysis", "E16", "Comps median EV/Revenue"),
    ("Comps Analysis", "F16", "Comps median PER"),
    ("Comps Analysis", "G16", "Comps median PBR"),
    ("Comps Analysis", "C27", "Comps implied price (EV/EBITDA)"),
    ("Comps Analysis", "C28", "Comps implied price (PER)"),
    ("Comps Analysis", "C29", "Normalized net income"),
]

SKIP_SUBSTRINGS = (
    "Generated by pipeline",     # timestamp
    "generated_at",
    "template_rev",
    "Peer prices as of",
)


def _val(wb, sheet, cell):
    if sheet not in wb.sheetnames:
        return "<no sheet>"
    try:
        return wb[sheet][cell].value
    except (ValueError, KeyError):
        return "<no cell>"


def _same(a, b, tol):
    if isinstance(a, (int, float)) and isinstance(b, (int, float)) \
            and not isinstance(a, bool) and not isinstance(b, bool):
        if b == 0:
            return abs(a) <= tol
        return abs(a - b) / max(abs(b), 1e-12) <= tol
    return (a if a is not None else "") == (b if b is not None else "")


def _fmt(v):
    if isinstance(v, float):
        return f"{v:,.4f}".rstrip("0").rstrip(".")
    if isinstance(v, int):
        return f"{v:,}"
    if v is None:
        return "-"
    return str(v)[:52]


def _skip(v):
    return isinstance(v, str) and any(s in v for s in SKIP_SUBSTRINGS)


def diff(ref_path, cand_path, tol, all_sheets):
    ref = openpyxl.load_workbook(ref_path, data_only=True)
    cand = openpyxl.load_workbook(cand_path, data_only=True)

    print(f"reference: {os.path.basename(ref_path)}")
    print(f"candidate: {os.path.basename(cand_path)}")
    print(f"tolerance: {tol:.4%} relative\n")
    print(f"{'項目':<46} {'reference':>16} {'candidate':>16}  {'差分':>14}")
    print("-" * 100)

    n_diff = 0
    for sheet, cell, label in KEY_CELLS:
        a, b = _val(ref, sheet, cell), _val(cand, sheet, cell)
        if a is None and b is None:
            continue
        ok = _same(b, a, tol)
        d = ""
        if isinstance(a, (int, float)) and isinstance(b, (int, float)) \
                and not isinstance(a, bool) and not isinstance(b, bool):
            d = _fmt(b - a)
        elif not ok:
            d = "≠"
        if not ok:
            n_diff += 1
        print(f"{('OK  ' if ok else 'DIFF') + ' ' + label:<46} "
              f"{_fmt(a):>16} {_fmt(b):>16}  {d:>14}")

    if all_sheets:
        print("\n" + "=" * 100)
        print("full sweep (every populated cell of every shared sheet)")
        print("=" * 100)
        shared = [s for s in ref.sheetnames if s in cand.sheetnames]
        only_ref = [s for s in ref.sheetnames if s not in cand.sheetnames]
        only_cand = [s for s in cand.sheetnames if s not in ref.sheetnames]
        if only_ref:
            print(f"  sheets only in reference: {only_ref}")
        if only_cand:
            print(f"  sheets only in candidate: {only_cand}")
        for sheet in shared:
            ws_a, ws_b = ref[sheet], cand[sheet]
            rows = max(ws_a.max_row, ws_b.max_row)
            cols = max(ws_a.max_column, ws_b.max_column)
            hits = []
            for r in range(1, rows + 1):
                for c in range(1, cols + 1):
                    a = ws_a.cell(row=r, column=c).value
                    b = ws_b.cell(row=r, column=c).value
                    if a is None and b is None:
                        continue
                    if _skip(a) or _skip(b):
                        continue
                    if not _same(b, a, tol):
                        hits.append((ws_a.cell(row=r, column=c).coordinate,
                                     a, b))
            print(f"\n  [{sheet}] {len(hits)} differing cell(s)")
            for coord, a, b in hits[:60]:
                print(f"    {coord:>6}  ref={_fmt(a):<40} cand={_fmt(b)}")
            if len(hits) > 60:
                print(f"    ... {len(hits) - 60} more")
            n_diff += len(hits)

    print("\n" + "=" * 100)
    print(f"differences: {n_diff}")
    return n_diff


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("reference")
    ap.add_argument("candidate")
    ap.add_argument("--tolerance", type=float, default=0.001,
                    help="relative tolerance for numeric cells (default 0.1%%)")
    ap.add_argument("--all-sheets", action="store_true",
                    help="also diff every populated cell of every shared sheet")
    a = ap.parse_args()
    for p in (a.reference, a.candidate):
        if not os.path.isfile(p):
            sys.exit(f"ERROR: not found: {p}")
    sys.exit(1 if diff(a.reference, a.candidate, a.tolerance, a.all_sheets) else 0)


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    main()
